export default {
  splash: require('./image/splash.png'),
  bg: require('./image/bg.png'),
  logo: require('./image/logo.png'),
  tv: require('./image/tv.png'),
  notification: require('./image/notification.png'),
  success: require('./image/success.png'),
  error: require('./image/error.png'),
  google: require('./image/google.png'),
  facebook: require('./image/facebook.png'),
  live: require('./image/live.png'),
  rightarrow: require('./image/rightarrow.png'),
  removesave: require('./image/removesave.png'),
  addsave: require('./image/addsave.png'),
};
